version: 2.1

node_image: &node_image
  circleci/node:8.9.1

executors:
  docker-exec:
    docker:
      - image: *node_image
        environment:
          TZ: Asia/Tokyo

jobs:
  lint:
    steps:
      executor: docker-exec
      working_directory: ~/imasparql_form
      - checkout
      - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
  # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
      - run: npm install
      - run:
        name: eslint
        command: npm run eslint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/imasparql_form
          paths: .

workflows:
  version: 2
  build:
    jobs:
      - lint
